// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Providers.Model.DataBase;

#nullable disable

namespace Providers.Migrations
{
    [DbContext(typeof(ProviderDB))]
    [Migration("20231111145602_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("Providers.Model.Entity.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Providers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Oleg and K.O"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Magomed Inc"
                        },
                        new
                        {
                            Id = 3,
                            Name = "At Olesya's"
                        },
                        new
                        {
                            Id = 4,
                            Name = "At Home"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Horns and hooves"
                        },
                        new
                        {
                            Id = 6,
                            Name = "The best company"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Another best company"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Midass"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Golden Path"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Fun beavers"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Pi 3.14"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
